// <auto-generated />
namespace PlaygroundProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedunnecessarynavproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedunnecessarynavproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201605261710068_removed unnecessary nav-property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
